# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x1a\x1fgoogle/protobuf/timestamp.proto\".\n\x08\x64uration\x12\x11\n\tstartTime\x18\x01 \x01(\t\x12\x0f\n\x07\x65ndTime\x18\x02 \x01(\t\"\xaf\x01\n\x08InitTask\x12\x0e\n\x06taskId\x18\x01 \x01(\x03\x12\x10\n\x08taskName\x18\x02 \x01(\t\x12\x0b\n\x03\x45TA\x18\x03 \x01(\t\x12\x1b\n\x06status\x18\x04 \x01(\x0e\x32\x0b.taskStatus\x12\x10\n\x08priority\x18\x05 \x01(\t\x12\x1b\n\x08\x64uration\x18\x06 \x01(\x0b\x32\t.duration\x12(\n\x04time\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1e\n\x0cInitResponse\x12\x0e\n\x06taskId\x18\x01 \x01(\x03*C\n\ntaskStatus\x12\x08\n\x04NONE\x10\x00\x12\x0f\n\x0bIN_PROGRESS\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x12\x0b\n\x07ON_HOLD\x10\x03\x32*\n\x05Tasks\x12!\n\x03\x61\x64\x64\x12\t.InitTask\x1a\r.InitResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKSTATUS']._serialized_start=305
  _globals['_TASKSTATUS']._serialized_end=372
  _globals['_DURATION']._serialized_start=47
  _globals['_DURATION']._serialized_end=93
  _globals['_INITTASK']._serialized_start=96
  _globals['_INITTASK']._serialized_end=271
  _globals['_INITRESPONSE']._serialized_start=273
  _globals['_INITRESPONSE']._serialized_end=303
  _globals['_TASKS']._serialized_start=374
  _globals['_TASKS']._serialized_end=416
# @@protoc_insertion_point(module_scope)
